- lib/apivore/rspec_matchers.rb
- spec/integration_spec.rb
This has the consequence that all response properties are assumed to be required (due to a quirk in json-schema) but will alert on extra undocumented properties, which we want and have identified as more important for now.
TODO: add a configuration option to allow either strict or non-strict validations, and find a way to remove the 'assume-required' assumption.
> change schema validation to STRICT

- lib/apivore/rspec_builder.rb
Updating apivore in Movie Service caused an exception to be thrown when used. Tracked this down to a missing require in `rspec_builder.rb`. Assume it's only an issue when the gem isn't already loaded in the parent app.
> Add require 'rspec/mocks' to fix crash.

- lib/apivore/rspec_builder.rb
- lib/apivore/rspec_matchers.rb
Usage: 
```ruby
be_consistent_with_swagger_at "example.com"
```
It will then then look at http://example.com/swagger.json, and check to make sure there are no inconsistencies.
> Add support for swagger consistency checks

- spec/data/07_missing_non-required_property.json
- spec/integration_spec.rb
@chrisrbnelson I've re-enabled this test because optional properties do work with the additionalProperties field, as you said. It seems to be inherited from json-schema rather than from Swagger 2.0, which doesn't seem to say anything about it specifically.  The test swagger file that uses it, 07_missing_non-required_property.json, does pass the swagger 2.0 validation though, so it seems to all work nicely together. Easier than I thought, thanks for pointing me in the right direction!
> re-enable optional property test using additionalProperties

- lib/apivore/rspec_builder.rb
- lib/apivore/rspec_matchers.rb
Usage:
```
apivore_check_consistency_with_swagger_at "api.westfield.io", "search"
```
If the only conflicts are in definitions that come from search service (in this case), then the tests will pass. If the conflicts involve more than one service, or a service that isn't "search", then the tests will fail, as they should.
This should be both forward and backward compatible with x-services in swagger.json, and the previous usage, ```apivore_check_consistency_with_swagger_at "api.westfield.io"```.
> Allow single service changes 1425962436

- lib/apivore/rspec_matchers.rb
- spec/integration_spec.rb
https://jira.westfieldlabs.com/browse/RTLR-194
Changing error output from:
```
Failure/Error: expect(response.body).to conform_to_the_documented_model_for(swagger, fragment)
'#/0' contained undefined properties: 'name'
```
to
```
Failure/Error: expect(response.body).to conform_to_the_documented_model_for(swagger, fragment)
'/api/services.json#/0' contained undefined properties: 'name'
```
to make it clearer that it is a json ref path in a particular response, because the '#/' doesn't seem very meaningful by itself. Is this an improvement on the above?
> FEATURE [RTLR-194] make error messages clearer

- README.md
- lib/apivore/rspec_builder.rb
- spec/rspec_builder_spec.rb
I think this covers the basic requirements of PEEPS-440 and PEEPS-441:
*Permit setup only on response codes*
*Permit base request arguments to be defined for all documented routes*
@jgalilee, could you please review and check that this satisfies the requirements you suggested? The implementation is a bit different, and allows for other combinations, but I think it gives the flexibility you were after.
Hopefully the test makes it clear how the setups work now.
If it looks good, I'll need to modify the readme for the expanded usage.
> Permit setup and substitution params on any combination of path, method, and response

- apivore.gemspec
- lib/apivore/rspec_matchers.rb
- spec/data/05_extra_properties.json
- spec/data/07_missing_non-required_property.json
- spec/integration_spec.rb
Optional properties should be represented in Swagger by specifying all properties under `properties`, and listing the required ones in `required`.
The previous usage of `additionalProperties` happened to work here, but was not picked up by swagger-codegen. Using `required` is the correct method.
The original misunderstanding in Apivore stemmed from the desire to catch undocumented properties in json data. It turns out that, by default, undocumented properties are accepted as valid in json-schema, and therefore by extension in Swagger 2.0.
To cause undocumented properties in an api response to trigger a validation failure `additionalProperties` must be explicitly set to `false` in the Swagger document, as in [this test example] (spec/data/05_extra_properties.json))
The result of the …
> [Feature, CNTR-358] Work out how to properly represent optional properties in Swagger

- apivore.gemspec
- lib/apivore.rb
I've come across the following error in two applications when I tried to move them over the the new version:
```
NoMethodError: undefined method `configure' for RSpec:Module
/Users/charles/westfield/apivore/lib/apivore.rb:6:in `<top (required)>'
/Users/charles/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
/Users/charles/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/charles/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `each'
/Users/charles/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `block in require'
/Users/charles/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each' …
```
> require rspec so RSpec.configure won't fail

- Gemfile.lock
- apivore.gemspec
This PR includes the correct files in the gemspec -- the previous 'fix' didn't work.
It also adds license information, and deals with a number of other warnings that occurred when building the gem.
> [Bug Fix] include correct files, and improve gemspec

- Gemfile.lock
- README.md
- apivore.gemspec
- data/draft04_schema.json
- data/swagger_2.0_schema.json
- lib/apivore.rb
- lib/apivore/rspec_matchers.rb
- spec/data/05_extra_properties.json
Previously Apivore used a modified version of the Swagger 2.0 spec that manually included the contents of the $refs to the draft04 schema. Forming this was a manual process. 
This PR uses the latest unmodified Swagger 2.0 spec and draft04 and takes advantage of a feature of `json-schema` that lets us register an external resource locally. This makes getting the latest version of either easier to update and include.
> Update Swagger 2.0 schema and include local draft04 to prevent network calls

- apivore.gemspec
- data/custom_schemata/westfield_api_standards.json
- lib/apivore/custom_schema_validator.rb
- lib/apivore/rspec_helpers.rb
- spec/data/08_untyped_definition.json
- spec/data/example_specs.rb
- spec/fixtures/application.rb
- spec/integration_spec.rb
- spec/request_spec.rb
In order to enforce the requirements from CNTR-743, add a method to validate swagger.json against additional (organisational specifc) json schemata.
CNTR-743 requirements:
* All entities defined in the `definitions` section must include an explicit `type: object` attribute. This forces the entity to be validated.
* All arrays must be explicitly 'typed', either via `$ref` to an entity that itself is typed (i.e. has `type:object`), or via an explicit `type: xxx` attribute in the `items` section of the array spec.
> [CNTR-746] Allow swagger validation against custom schemata

- apivore.gemspec
- data/swagger_2.0_schema.json
- lib/apivore/custom_schema_validator.rb
- spec/data/example_specs.rb
- spec/request_spec.rb
This includes the updated swagger 2.0 spec, but also a revision on how the example custom schema validation should be used. It uses a constant to point to the Westfield custom schema which is included in the gem as an 'example'.
> Tidy Custom Schema validation usage, and use latest swagger 2.0 spec

- lib/apivore/swagger.rb
As they don't correspond to resource routes, currently this just
includes `parameters`.
See https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#path-item-object
Addresses #59
> Skip path items that are not HTTP verbs

- spec/data/sample2.0.json
This adds an example of the feature provided by https://github.com/westfieldlabs/apivore/pull/60 to the example swagger used in the tests.
> Update test/example swagger to include path parameters

- lib/apivore/swagger_checker.rb
- lib/apivore/validator.rb
This makes the last response available on the SwaggerChecker, the `subject` of the tests.
This will help with debugging, and enable
`expect(subject.response).to <something>` additional verifications, perhaps to ensure a response is not empty and trivially passing the json schema validations.
> Better debugging and response access

- apivore.gemspec
- lib/apivore/swagger_checker.rb
- lib/apivore/validator.rb
@adamcohen, what do you think of this output format? It's a combination of what I was trying to do with my earlier response output that only worked for response code diffs, and your latest PR. The debug output is attached to the rspec failure output now,
example output:
`rspec spec/data/example_specs.rb` =>
```
API testing scenarios
unimplemented path
fails (FAILED - 1)
mismatched property type
fails (FAILED - 2)
unexpected http response
fails (FAILED - 3)
extra properties
fails (FAILED - 4)
also fails (FAILED - 5)
missing required
fails (FAILED - 6)
also fails (FAILED - 7)
missing non-required
passes
also passes
fails custom validation
passes
fails (FAILED - 8)
Failures:
1) API testing scenarios unimplemented path fails
Failure/Error: expect(subject).to validate(:get, …
```
> Print response body when test fails (v2)

- apivore.gemspec
Build is failing because of a conflict between `activesupport` dependency versions. This PR moves the  dev dependency to take into account the ruby version as well.
cc: @gwshaw
> Fix bundler dependency issues

- lib/apivore/rails_shim.rb
- lib/apivore/validator.rb
- spec/integration_spec.rb
- spec/rails_shim_spec.rb
This approach uses a Rails Shim to handle formulating the params for a request to the app in integration tests, as discussed in https://github.com/westfieldlabs/apivore/pull/96#issuecomment-273587222, modeled after https://github.com/thoughtbot/shoulda-matchers/pull/989/files#diff-f46c5b61347eb8f9749762252d06fb52R29 but modified because we have to worry about headers as well (hence the Arrays and splatting).
I briefly considered moving the entire request out to a shimming object, but for whatever reason I couldn't get that to work.  If someone else can, it might be a cleaner approach.  Not sure it's worth driving ourselves crazy over, though.
I had some trouble getting older versions of Ruby to bundle locally for testing, but recent builds seem to work on Travis, so in this case I'm going …
> Fix Rails 5 params deprecation warning

- apivore.gemspec
- lib/apivore/version.rb
- Modify how the version is being set
- Remove extraneous date in gemspec [specification-reference](http://guides.rubygems.org/specification-reference/)
- Bump version for https://github.com/westfieldlabs/apivore/pull/102
> Bump version to 1.6.2
